# Generated by Django 4.1.6 on 2023-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_sinopse', models.CharField(max_length=200)),
                ('ds_titulo', models.CharField(max_length=45)),
                ('valor', models.FloatField()),
                ('fotoCaminho', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_produto', models.CharField(max_length=45)),
                ('cd_produto', models.CharField(max_length=45)),
                ('qt_produto', models.IntegerField()),
                ('bo_ativo', models.CharField(max_length=45)),
            ],
        ),
    ]
