# Generated by Django 4.1.5 on 2023-02-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manga',
            name='estado',
            field=models.CharField(default='', max_length=5),
        ),
    ]
