# Generated by Django 4.1.5 on 2023-03-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0002_manga_cidade_manga_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produto',
        ),
    ]
