# Generated by Django 4.1.6 on 2023-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0002_manga_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='localizacao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
