# Generated by Django 4.1.5 on 2023-03-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0002_alter_endereco_cep_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_forma_pagamento', models.CharField(blank=True, default=None, max_length=9, null=True)),
                ('id_endereco_entrega', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('dh_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.usuario')),
            ],
            options={
                'ordering': ['-dh_pedido'],
            },
        ),
    ]
