# Generated by Django 4.1.5 on 2023-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0002_alter_endereco_cep_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.CharField(max_length=5)),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
    ]
