# Generated by Django 4.1.5 on 2023-03-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0003_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emanga.usuario'),
            preserve_default=False,
        ),
    ]
