# Generated by Django 4.1.5 on 2023-03-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dh_criacao', models.DateTimeField(auto_now_add=True)),
                ('dh_vencimento', models.DateTimeField()),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nr_parcelas', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='valor',
            new_name='vl_total',
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dh_pagamento', models.DateTimeField()),
                ('vl_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.cobranca')),
            ],
        ),
        migrations.AddField(
            model_name='cobranca',
            name='id_forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.formapagamento'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.pedido'),
        ),
    ]
