# Generated by Django 4.1.6 on 2023-02-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0003_manga_localizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='localizacao',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='manga',
            name='estado',
            field=models.CharField(default='', max_length=5),
        ),
    ]
