# Generated by Django 4.1.6 on 2023-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0004_rename_localizacao_manga_cidade_manga_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
