# Generated by Django 4.1.5 on 2023-03-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0004_cobranca_formapagamento_rename_valor_pedido_vl_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_titulo', models.CharField(max_length=45)),
                ('ds_sinopse', models.CharField(max_length=200)),
                ('cidade', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=5)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField(default=0)),
                ('fotoCaminho', models.CharField(max_length=700)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qt_pedido', models.CharField(max_length=2)),
                ('vl_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.manga')),
            ],
        ),
    ]
