# Generated by Django 4.1.5 on 2023-03-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0005_manga_rename_user_id_pedido_user_itempedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranca',
            old_name='id_forma_pagamento',
            new_name='forma_pagamento',
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='id_produto',
            new_name='manga',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='id_cobranca',
            new_name='cobranca',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_endereco_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_forma_pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
