# Generated by Django 4.1.5 on 2023-03-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0005_alter_cartao_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.usuario'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dh_pedido', models.DateTimeField(auto_now_add=True)),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregue', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_titulo', models.CharField(max_length=45)),
                ('ds_sinopse', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('fotoCaminho', models.CharField(max_length=700)),
                ('disponivel', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qt_pedido', models.CharField(max_length=2)),
                ('vl_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.manga')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanga.pedido')),
            ],
        ),
    ]
