# Generated by Django 4.1.5 on 2023-03-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0006_rename_id_forma_pagamento_cobranca_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cobranca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.cobranca'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.formapagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.endereco'),
        ),
    ]
