# Generated by Django 4.1.6 on 2023-03-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0006_alter_manga_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='disponivel',
        ),
    ]
