# Generated by Django 4.1.6 on 2023-03-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0007_remove_manga_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='disponivel',
            field=models.IntegerField(default=1),
        ),
    ]
