# Generated by Django 4.1.5 on 2023-03-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0007_remove_cobranca_pedido_remove_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cobranca',
        ),
        migrations.AddField(
            model_name='cobranca',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emanga.pedido'),
        ),
    ]
