# Generated by Django 4.1.5 on 2023-04-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0008_remove_pedido_cobranca_cobranca_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='vl_pagamento',
            new_name='vl_fatura',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='nr_parcela',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='vl_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='dh_vencimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='dh_pagamento',
            field=models.DateTimeField(null=True),
        ),
    ]
