# Generated by Django 4.1.6 on 2023-03-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0008_manga_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='manga',
            name='ativo',
            field=models.CharField(default='sim', max_length=3),
        ),
    ]
