# Generated by Django 4.1.5 on 2023-04-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0009_rename_vl_pagamento_pagamento_vl_fatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
