# Generated by Django 4.1.6 on 2023-03-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanga', '0009_remove_manga_disponivel_manga_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='ativo',
        ),
    ]
